name: New commit pushed and receive pull request

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@main
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip pipenv invoke
          inv env.init-dev --no-pre-commit

      - name: Style check
        run: |
          inv style

      - name: Check vulnerability
        run: |
          inv secure

      - name: Run tests
        run: |
          inv test -a
