name: python check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: Style check
        run: |
          pipenv run black . --check
          pipenv run flake8 --max-line-length=88 .
      - name: Security Check
        run: |
          pipenv check
